<?php

namespace Controller;

/**
 * Created by PhpStorm.
 * User: stas
 * Date: 21.05.16
 * Time: 12:31
 */

class Rectangle extends Square
{
 public function area($side_a, $side_b)
 {
     echo "Rectangle " ;
     return parent::area($side_a, $side_b); // TODO: Change the autogenerated stub
 }
}